import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    tokenIdentifier: v.string(),
    name: v.optional(v.string()),
    email: v.optional(v.string()),
    businessName: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    currency: v.optional(v.string()),
    taxNumber: v.optional(v.string()),
  }).index("by_token", ["tokenIdentifier"]),

  clients: defineTable({
    userId: v.id("users"),
    name: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    company: v.optional(v.string()),
    notes: v.optional(v.string()),
  }).index("by_user", ["userId"]).index("by_user_name", ["userId", "name"]),

  products: defineTable({
    userId: v.id("users"),
    name: v.string(),
    description: v.optional(v.string()),
    price: v.number(),
    currency: v.string(),
    unit: v.optional(v.string()),
    category: v.optional(v.string()),
    isService: v.boolean(),
  }).index("by_user", ["userId"]).index("by_user_name", ["userId", "name"]),

  quotations: defineTable({
    userId: v.id("users"),
    clientId: v.id("clients"),
    quoteNumber: v.string(),
    status: v.union(v.literal("draft"), v.literal("sent"), v.literal("accepted"), v.literal("declined"), v.literal("expired")),
    issueDate: v.string(),
    expiryDate: v.optional(v.string()),
    currency: v.string(),
    items: v.array(v.object({ productId: v.optional(v.id("products")), description: v.string(), quantity: v.number(), unitPrice: v.number(), total: v.number() })),
    subtotal: v.number(),
    taxRate: v.optional(v.number()),
    taxAmount: v.optional(v.number()),
    discountRate: v.optional(v.number()),
    discountAmount: v.optional(v.number()),
    total: v.number(),
    notes: v.optional(v.string()),
    terms: v.optional(v.string()),
  }).index("by_user", ["userId"]).index("by_user_status", ["userId", "status"]).index("by_user_client", ["userId", "clientId"]),

  invoices: defineTable({
    userId: v.id("users"),
    clientId: v.id("clients"),
    quotationId: v.optional(v.id("quotations")),
    invoiceNumber: v.string(),
    status: v.union(v.literal("draft"), v.literal("sent"), v.literal("paid"), v.literal("overdue"), v.literal("cancelled")),
    issueDate: v.string(),
    dueDate: v.optional(v.string()),
    currency: v.string(),
    items: v.array(v.object({ productId: v.optional(v.id("products")), description: v.string(), quantity: v.number(), unitPrice: v.number(), total: v.number() })),
    subtotal: v.number(),
    taxRate: v.optional(v.number()),
    taxAmount: v.optional(v.number()),
    discountRate: v.optional(v.number()),
    discountAmount: v.optional(v.number()),
    total: v.number(),
    paidAmount: v.optional(v.number()),
    paidDate: v.optional(v.string()),
    notes: v.optional(v.string()),
    terms: v.optional(v.string()),
  }).index("by_user", ["userId"]).index("by_user_status", ["userId", "status"]).index("by_user_client", ["userId", "clientId"]),

  receipts: defineTable({
    userId: v.id("users"),
    clientId: v.id("clients"),
    invoiceId: v.optional(v.id("invoices")),
    receiptNumber: v.string(),
    issueDate: v.string(),
    currency: v.string(),
    items: v.array(v.object({ description: v.string(), quantity: v.number(), unitPrice: v.number(), total: v.number() })),
    subtotal: v.number(),
    taxAmount: v.optional(v.number()),
    discountAmount: v.optional(v.number()),
    total: v.number(),
    paymentMethod: v.optional(v.string()),
    notes: v.optional(v.string()),
  }).index("by_user", ["userId"]).index("by_user_invoice", ["userId", "invoiceId"]),
});
